### ISSUE TITLE
@nestjs/ng-universal: 2.0.0 fails with TypeError: provideModuleMap is not a function

### ISSUE THREAD

**Issue by mfursov** [nestjs/ng-universal#114]
## 
[X ] Regression 

## Current behavior
The old version (1.2.0) works, while the updated one (2.0.0) throws exception in runtime:
<pre>
[Nest] 120396   - 08/01/2019, 3:27 PM   [ExceptionsHandler] provideModuleMap is not a function +226ms
TypeError: provideModuleMap is not a function
    at View.app.engine (/home/fmike/work/tabius/node_modules/@nestjs/ng-universal/dist/utils/setup-universal.utils.js:23:17)
    at View.render (/home/fmike/work/tabius/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/fmike/work/tabius/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/fmike/work/tabius/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/fmike/work/tabius/node_modules/express/lib/response.js:1012:7)
    at app.get (/home/fmike/work/tabius/node_modules/@nestjs/ng-universal/dist/angular-universal.module.js:60:66)
    at Layer.handle [as handle_request] (/home/fmike/work/tabius/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/fmike/work/tabius/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/fmike/work/tabius/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/fmike/work/tabius/node_modules/express/lib/router/layer.js:95:5)

</pre>

## Expected behavior
To work as before

## Minimal reproduction of the problem with instructions
Replace 1.2.0 to 2.0.0 in this project: 
https://github.com/tabius/tabius

## Environment
Linux.

**Comment by mfursov** [comment]
I have to make this change to make the v2.0.0 work in my project. With v1.2.0 this was not necessary.

https://github.com/tabius/tabius/commit/de12e48603cd797720f0b1772ba9c9cf3d81327d

**Comment by kamilmysliwiec** [comment]
You have to follow this upgrade guide - https://github.com/angular/universal/blob/master/docs/v8-upgrade-guide.md 

The breaking changes were introduced by Angular 8 release
