### ISSUE TITLE
FroalaViewDirective_Factory is not compatible with Angular Dependency Injection

### ISSUE THREAD

**Issue by Aventrue** [nestjs/ng-universal#389]
After I migrate my application to angular 9 I get following error on server side rendering: 

Error: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.      
This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.
    at ɵɵinvalidFactoryDep (C:\Git\bigbang\Truedo.Client\dist\server\main.js:71114:11)
    at NodeInjectorFactory.FroalaViewDirective_Factory [as factory] (ng:///FroalaViewDirective/ɵfac.js:5:47)
    at getNodeInjectable (C:\Git\bigbang\Truedo.Client\dist\server\main.js:75172:44)
    at instantiateAllDirectives (C:\Git\bigbang\Truedo.Client\dist\server\main.js:81372:27)
    at createDirectivesInstances (C:\Git\bigbang\Truedo.Client\dist\server\main.js:80584:5)
    at ɵɵelementStart (C:\Git\bigbang\Truedo.Client\dist\server\main.js:89233:9)
    at Module.ɵɵelement (C:\Git\bigbang\Truedo.Client\dist\server\main.js:89289:5)
    at TextViewComponent_div_13_Template (C:\Git\bigbang\Truedo.Client\dist\server\main.js:274452:8)
    at executeTemplate (C:\Git\bigbang\Truedo.Client\dist\server\main.js:80544:9)
    at renderView (C:\Git\bigbang\Truedo.Client\dist\server\main.js:80314:13)

How can I fix that? It's really important that ssr works.

**Comment by Aventrue** [comment]
If I make an own directive inside my module it works:

@Directive({
  selector: "[froalaView]",
})
export class frvDirective {
  private _element: HTMLElement;

  constructor(private renderer: Renderer2, element: ElementRef) {
    this._element = element.nativeElement;
  }

  // update content model as it comes
  @Input() set froalaView(content: string) {
    this._element.innerHTML = content;
  }

  ngAfterViewInit() {
    this.renderer.addClass(this._element, "fr-view");
  }
}

What can that be??

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
